# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
main:
  - name: About
    url: '/about'
    weight: 10
  - name: Team
    parent: About
    url: '/author'
    weight: 11
  - name: Media
    parent: About
    url: '/news'
    weight: 13

  - name: Research Areas
    url: '/research'
    weight: 20
  - name: 'Maternal & Child Health'
    parent: Research Areas
    url: '/research/reproductive-justice'
    weight: 21
  - name: Education
    parent: Research Areas
    url: '/research/education'
    weight: 22
  - name: ACEs
    parent: Research Areas
    url: '/research/aces'
    weight: 23
  - name: Drug Overdose
    parent: Research Areas
    url: '/research/overdose'
    weight: 24
  - name: Interpersonal Violence
    parent: Research Areas
    url: '/research/violence'
    weight: 25
 
  - name: 'Law & Policy'
    url: '/advocacy'
    weight: 30
  - name: Legal Projects
    parent: 'Law & Policy'
    url: '/legal'
    weight: 31
  - name: Policy Briefs
    parent: 'Law & Policy'
    url: '/policy-briefs'
    weight: 33


  - name: Blog
    url: '/post'
    weight: 40
  - name: BD4SJ on Medium
    parent: Blog
    url: 'https://bigdataforsocialjustice.medium.com/'
    weight: 41

  - name: Publications
    url: '/publication'
    weight: 50

  - name: Resources
    url: '/resources'
    weight: 60
  - name: Datasets
    parent: Resources
    url: '/resources/datasets'
    weight: 61
  - name: Tutorials
    parent: Resources
    url: '/courses'
    weight: 62
  - name: Learning
    parent: Resources  
    url: '/resources/resources'
    weight: 63
    
  - name: Join Us
    url: '/join'
    weight: 70
  - name: Openings
    parent: Join Us
    url: '/opportunities/vacancies'
    weight: 71
  - name: How to Apply
    parent: Join Us
    url: '/opportunities/application-guide'
    weight: 72
  - name: Undergraduate Students
    parent: Join Us
    url: '/opportunities/student-projects'
    weight: 73
 
  - name: Contact
    url: '#contact'
    weight: 100

