main:
  - name: Home
    url: '/'
    weight: 1

  - name: Research Areas
    identifier: research_areas
    url: '/research/'
    weight: 10

  - name: Violence Across the Lifespan
    parent: research_areas
    url: '/research/violence/'
    weight: 11

  - name: Adverse Childhood Experiences
    parent: research_areas
    url: '/research/aces/'
    weight: 12

  - name: Drug Use, Overdose & Policy
    parent: research_areas
    url: '/research/overdose/'
    weight: 13

  - name: Education & Youth Safety
    parent: research_areas
    url: '/research/education/'
    weight: 14

  - name: Maternal & Child Health
    parent: research_areas
    url: '/research/reproductive-justice/'
    weight: 15

  - name: Research
    identifier: research
    url: '/research/'
    weight: 20

  - name: Publications
    parent: research
    url: '/publication/'
    weight: 21

  - name: Conference Presentations
    parent: research
    url: '/presentations/'
    weight: 22

  - name: Policy Briefs
    parent: research
    url: '/policy-briefs/'
    weight: 23

  - name: Lab Members
    identifier: community
    url: '/community/'
    weight: 30

  - name: Faculty
    parent: community
    url: '/community/faculty/'
    weight: 31

  - name: Graduate Students
    parent: community
    url: '/community/graduate/'
    weight: 32

  - name: Undergraduates
    parent: community
    url: '/community/undergraduates/'
    weight: 33

  - name: Works in Progress
    identifier: works_in_progress
    url: '/works-in-progress/'
    weight: 40

  - name: Research
    parent: works_in_progress
    url: '/works-in-progress/'
    weight: 41

  - name: "  • Manuscripts in Progress"
    parent: works_in_progress
    url: '/works-in-progress/manuscripts/'
    weight: 42

  - name: "  • Presentations"
    parent: works_in_progress
    url: '/works-in-progress/presentations/'
    weight: 43

  - name: Teaching
    parent: works_in_progress
    url: '#'
    weight: 44

  - name: Community
    parent: works_in_progress
    url: '#'
    weight: 45

  - name: "  • Consulting"
    parent: works_in_progress
    url: '#'
    weight: 46

  - name: Resources
    identifier: resources
    url: '/resources/'
    weight: 50

  - name: Data & Code
    parent: resources
    url: '/data-code/'
    weight: 51

  - name: Datasets
    parent: resources
    url: '/resources/datasets/'
    weight: 52

  - name: Tutorials
    parent: resources
    url: '/resources/tutorials/'
    weight: 53

  - name: Blog
    url: 'https://bigdataforsocialjustice.medium.com/'
    weight: 55

  - name: Contact
    url: '#contact'
    weight: 60
