main:
  - name: Home
    url: '/'
    weight: 1

  - name: About Us
    identifier: about_us
    url: '/about/'
    weight: 5

  - name: History
    parent: about_us
    url: '#'
    weight: 6

  - name: Our Work
    parent: about_us
    url: '/our-work/'
    weight: 7

  - name: Shared Goals & Values
    parent: about_us
    url: '/community/'
    weight: 8

  - name: Research
    identifier: research
    url: '/research/'
    weight: 20

  - name: Publications
    parent: research
    url: '/publication/'
    weight: 21

  - name: Conference Presentations
    parent: research
    url: '/presentations/'
    weight: 22

  - name: Policy Briefs
    parent: research
    url: '/policy-briefs/'
    weight: 23

  - name: Lab Members
    url: '/people/'
    weight: 30

  - name: News
    url: '/news/'
    weight: 35

  - name: Works in Progress
    identifier: works_in_progress
    url: '/works-in-progress/'
    weight: 40

  - name: Research
    parent: works_in_progress
    url: '/works-in-progress/'
    weight: 41

  - name: "  • Manuscripts in Progress"
    parent: works_in_progress
    url: '/works-in-progress/manuscripts/'
    weight: 42

  - name: "  • Presentations"
    parent: works_in_progress
    url: '/works-in-progress/presentations/'
    weight: 43

  - name: Teaching
    parent: works_in_progress
    url: '#'
    weight: 44

  - name: Community
    parent: works_in_progress
    url: '#'
    weight: 45

  - name: "  • Consulting"
    parent: works_in_progress
    url: '#'
    weight: 46

  - name: Resources
    identifier: resources
    url: '/resources/'
    weight: 50

  - name: Data & Code
    parent: resources
    url: '/data-code/'
    weight: 51

  - name: Datasets
    parent: resources
    url: '/resources/datasets/'
    weight: 52

  - name: Tutorials
    parent: resources
    url: '/resources/tutorials/'
    weight: 53

  - name: Blog
    url: '/post/'
    weight: 55

  - name: Contact
    url: '#contact'
    weight: 60
