- title: Dr. John Doe
  groups:
    - Principal Investigators
  role: Lead Researcher
  social: [twitter: "@johndoe", linkedin: "john-doe"]
- title: Jane Smith
  groups:
    - Grad Students
  role: PhD Candidate
  social: [twitter: "@janesmith"]
