<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="ISSUES">
<meta name="dcterms.date" content="2025-07-10">

<title>Latent Class Analysis in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="lca_files/libs/clipboard/clipboard.min.js"></script>
<script src="lca_files/libs/quarto-html/quarto.js"></script>
<script src="lca_files/libs/quarto-html/popper.min.js"></script>
<script src="lca_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="lca_files/libs/quarto-html/anchor.min.js"></script>
<link href="lca_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lca_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="lca_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="lca_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="lca_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Latent Class Analysis in R</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>ISSUES </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 10, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Latent Class Analysis (LCA) is a <strong>person-centered, categorical latent variable modeling approach</strong> used to identify unobserved subgroups within a population based on response patterns across multiple observed categorical variables. This tutorial introduces LCA using R, focusing on practical implementation, interpretation, and extensions (excluding Bayesian methods). Specifically, it covers (and its a work in progress):</p>
<ul>
<li><p>Standard LCA using poLCA (categorical variables)</p></li>
<li><p>Continuous latent profile analysis using tidyLPA</p></li>
<li><p>Multigroup LCA using subgroup splits (male/female)</p></li>
<li><p>Multilevel (random-effects) LCA using randomLCA</p></li>
</ul>
</section>
<section id="introduction-1" class="level1">
<h1>Introduction</h1>
<p>Latent Class Analysis (LCA) is a statistical method used to identify unobserved (latent) subgroups within a population based on individual response patterns across a set of categorical variables. Unlike variable-centered approaches like regression or factor analysis, LCA is person-centered—it aims to classify individuals into mutually exclusive, exhaustive latent classes. This method is widely used in psychology, public health, sociology, and education to uncover typologies or behavioral subgroups.</p>
<p>This tutorial will walk you through the theory, implementation, and interpretation of LCA in R using the <code>poLCA</code>, <code>tidyLPA</code>, and <code>randomLCA</code> packages. We will explore model selection, result interpretation, visualization, and extensions such as multigroup and multilevel LCA.</p>
<p>You should make sure to read some key papers using LCA as well as LCA tutorials in R. This is only a starting point. <a href="../..\static/uploads/LCASTU.pptx">My lecture notes are here</a>.</p>
</section>
<section id="libraries-and-installation" class="level1">
<h1>Libraries and Installation</h1>
<p>You will need to install and load several packages:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(c("poLCA", "tidyLPA", "flexmix", "randomLCA", "dplyr", "ggplot2", "tibble"))</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(poLCA)       <span class="co"># For classical latent class models with categorical indicators</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyLPA)     <span class="co"># For mixture models with continuous indicators (tidy syntax)</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(flexmix)     <span class="co"># For latent class regression</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomLCA)   <span class="co"># For multilevel or random-effects LCA</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="simulated-categorical-data-for-polca" class="level1">
<h1>Simulated Categorical Data for <code>poLCA</code></h1>
<section id="code-explanation" class="level4">
<h4 class="anchored" data-anchor-id="code-explanation">Code explanation</h4>
<p>This sets the random number generator seed to 123. It ensures reproducibility, meaning that every time this code is run, it produces the exact same random sample. Without this line, the numbers would change every time.</p>
<p>Then we create a <code>tibble</code> object (i.e., a dataframe) and assign it to an object called categorical data. The code then creates a simulated dataset named categorical_data with 500 rows and 4 categorical variables we are calling symptoms. Each symptom is randomly generated to have either 2 or 3 response categories. This simulated data is used for demonstration purposes in latent class analysis. <em>Note:</em> sampled values are <strong>with replacement.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>categorical_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">symptom1 =</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="dv">500</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">symptom2 =</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">500</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">symptom3 =</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="dv">500</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">symptom4 =</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">500</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="note-on-the-dataset" class="level4">
<h4 class="anchored" data-anchor-id="note-on-the-dataset">Note on the dataset</h4>
<p>First note that <code>poLCA</code> expects the coding to start at 1, and not 0.</p>
<p>Here, binary items (symptom1, symptom3) are explicitly coded as:</p>
<ul>
<li>1 = Yes (the person has the symptom)</li>
<li>2 = No (the person does not have the symptom)</li>
</ul>
<p>Multinomial items (symptom2, symptom4) reflect three unordered or ordinal response categories (e.g., levels of severity or type of symptom presentation), though the specific meaning of 1–3 is not defined in the code and would typically depend on survey or assessment documentation.</p>
</section>
</section>
<section id="lca-with-polca" class="level1">
<h1>LCA with <code>poLCA</code></h1>
<section id="specifying-the-model" class="level2">
<h2 class="anchored" data-anchor-id="specifying-the-model">Specifying the Model</h2>
<p>The <code>poLCA</code> function is used to do the latent variable modeling in this example. IMHO, this package is extremely limited, however it is fine for the most basic of analyses (which are not that basic).</p>
<p>The model takes the following form. <code>cbind</code> binds or merges the columns you want to use for the analysis, here the four symptoms. As with all models in R, the <code>~ 1</code> represents on intercept-only model (i.e., no covariates).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">cbind</span>(symptom1, symptom2, symptom3, symptom4) <span class="sc">~</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="fitting-models-with-2-to-4-classes" class="level2">
<h2 class="anchored" data-anchor-id="fitting-models-with-2-to-4-classes">Fitting Models with 2 to 4 Classes</h2>
<p>LCA is iterative. You must estimate several models and chose the best-fitting. Here I am estimating three models representing LC two through four. Why are we not estimating one latent class?</p>
<p>We stop when we get the best-fiting model as shown below in the model fit comparison section.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>model_2class <span class="ot">&lt;-</span> <span class="fu">poLCA</span>(f, <span class="at">data =</span> categorical_data, <span class="at">nclass =</span> <span class="dv">2</span>, <span class="at">maxiter =</span> <span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in matrix(sqrt(diag(VCE.beta)), nrow = ncol(x), ncol = (R - 1)): data
length differs from size of matrix: [100 != 1 x 1]</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Conditional item response (column) probabilities,
 by outcome variable, for each class (row) 
 
$symptom1
           Pr(1)  Pr(2)
class 1:  0.5122 0.4878
class 2:  0.5387 0.4613

$symptom2
           Pr(1)  Pr(2)  Pr(3)
class 1:  0.1009 0.5185 0.3806
class 2:  0.6342 0.0031 0.3627

$symptom3
           Pr(1)  Pr(2)
class 1:  0.5585 0.4415
class 2:  0.4544 0.5456

$symptom4
           Pr(1)  Pr(2)  Pr(3)
class 1:  0.3600 0.2618 0.3782
class 2:  0.2842 0.4572 0.2586

Estimated class population shares 
 0.6305 0.3695 
 
Predicted class memberships (by modal posterior prob.) 
 0.646 0.354 
 
========================================================= 
Fit for 2 latent classes: 
========================================================= 
number of observations: 500 
number of estimated parameters: 13 
residual degrees of freedom: 22 
maximum log-likelihood: -1783.205 
 
AIC(2): 3592.41
BIC(2): 3647.199
G^2(2): 22.85481 (Likelihood ratio/deviance statistic) 
X^2(2): 23.1458 (Chi-square goodness of fit) 
 
ALERT: iterations finished, MAXIMUM LIKELIHOOD NOT FOUND 
 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>model_3class <span class="ot">&lt;-</span> <span class="fu">poLCA</span>(f, <span class="at">data =</span> categorical_data, <span class="at">nclass =</span> <span class="dv">3</span>, <span class="at">maxiter =</span> <span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Conditional item response (column) probabilities,
 by outcome variable, for each class (row) 
 
$symptom1
           Pr(1)  Pr(2)
class 1:  0.5182 0.4818
class 2:  0.0108 0.9892
class 3:  0.6649 0.3351

$symptom2
           Pr(1)  Pr(2)  Pr(3)
class 1:  0.2190 0.3957 0.3854
class 2:  0.7412 0.0160 0.2428
class 3:  0.6626 0.0000 0.3374

$symptom3
           Pr(1)  Pr(2)
class 1:  0.5580 0.4420
class 2:  0.0000 1.0000
class 3:  0.4174 0.5826

$symptom4
           Pr(1) Pr(2)  Pr(3)
class 1:  0.3664 0.263 0.3706
class 2:  0.1777 0.000 0.8223
class 3:  0.1641 0.834 0.0019

Estimated class population shares 
 0.8276 0.0329 0.1395 
 
Predicted class memberships (by modal posterior prob.) 
 0.866 0.034 0.1 
 
========================================================= 
Fit for 3 latent classes: 
========================================================= 
number of observations: 500 
number of estimated parameters: 20 
residual degrees of freedom: 15 
maximum log-likelihood: -1779.102 
 
AIC(3): 3598.204
BIC(3): 3682.496
G^2(3): 14.64944 (Likelihood ratio/deviance statistic) 
X^2(3): 14.85317 (Chi-square goodness of fit) 
 
ALERT: iterations finished, MAXIMUM LIKELIHOOD NOT FOUND 
 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>model_4class <span class="ot">&lt;-</span> <span class="fu">poLCA</span>(f, <span class="at">data =</span> categorical_data, <span class="at">nclass =</span> <span class="dv">4</span>, <span class="at">maxiter =</span> <span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Conditional item response (column) probabilities,
 by outcome variable, for each class (row) 
 
$symptom1
           Pr(1)  Pr(2)
class 1:  0.0000 1.0000
class 2:  0.9999 0.0001
class 3:  0.7750 0.2250
class 4:  0.0491 0.9509

$symptom2
           Pr(1)  Pr(2)  Pr(3)
class 1:  0.4095 0.2734 0.3171
class 2:  0.4256 0.1683 0.4061
class 3:  0.2062 0.3962 0.3975
class 4:  0.2744 0.3784 0.3472

$symptom3
           Pr(1)  Pr(2)
class 1:  0.0000 1.0000
class 2:  0.4431 0.5569
class 3:  0.5328 0.4672
class 4:  0.9740 0.0260

$symptom4
           Pr(1)  Pr(2)  Pr(3)
class 1:  0.2456 0.3441 0.4103
class 2:  0.0778 0.8830 0.0392
class 3:  0.4873 0.0354 0.4773
class 4:  0.3235 0.4227 0.2538

Estimated class population shares 
 0.1747 0.188 0.417 0.2202 
 
Predicted class memberships (by modal posterior prob.) 
 0.224 0.182 0.34 0.254 
 
========================================================= 
Fit for 4 latent classes: 
========================================================= 
number of observations: 500 
number of estimated parameters: 27 
residual degrees of freedom: 8 
maximum log-likelihood: -1775.597 
 
AIC(4): 3605.193
BIC(4): 3718.987
G^2(4): 7.638293 (Likelihood ratio/deviance statistic) 
X^2(4): 7.633208 (Chi-square goodness of fit) 
 
ALERT: iterations finished, MAXIMUM LIKELIHOOD NOT FOUND 
 </code></pre>
</div>
</div>
</section>
<section id="model-fit-comparison" class="level2">
<h2 class="anchored" data-anchor-id="model-fit-comparison">Model Fit Comparison</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>bic_values <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">BIC_2 =</span> model_2class<span class="sc">$</span>bic,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">BIC_3 =</span> model_3class<span class="sc">$</span>bic,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">BIC_4 =</span> model_4class<span class="sc">$</span>bic</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(bic_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   BIC_2    BIC_3    BIC_4 
3647.199 3682.496 3718.987 </code></pre>
</div>
</div>
<p>Lower BIC values indicate better fit. Select the number of classes accordingly.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 3%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>LL</th>
<th>AIC</th>
<th>BIC</th>
<th>G²</th>
<th>X²</th>
<th>Params</th>
<th>df</th>
<th>Preferred?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2-class</td>
<td>-1783.21</td>
<td><strong>3592.41</strong></td>
<td><strong>3647.20</strong></td>
<td>22.85</td>
<td>23.15</td>
<td>13</td>
<td>22</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>3-class</td>
<td>-1779.10</td>
<td>3598.20</td>
<td>3682.50</td>
<td>14.65</td>
<td>14.85</td>
<td>20</td>
<td>15</td>
<td>No</td>
</tr>
<tr class="odd">
<td>4-class</td>
<td>-1775.60</td>
<td>3605.19</td>
<td>3718.99</td>
<td>7.64</td>
<td>7.63</td>
<td>27</td>
<td>8</td>
<td>No</td>
</tr>
</tbody>
</table>
<section id="how-to-compute-entropy" class="level3">
<h3 class="anchored" data-anchor-id="how-to-compute-entropy">How to compute entropy</h3>
<p><code>poLCA</code> does NOT compute entropy, which is technically not a fit statistic but a measure of classification certainty.</p>
<p>To compute entropy (should always be included, and should be high):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>entropy<span class="ot">&lt;-</span><span class="cf">function</span> (p) <span class="fu">sum</span>(<span class="sc">-</span>p<span class="sc">*</span><span class="fu">log</span>(p))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>error_prior <span class="ot">&lt;-</span> <span class="fu">entropy</span>(model_2class<span class="sc">$</span>P) <span class="co"># Class proportions</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>error_post <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">apply</span>(model_2class<span class="sc">$</span>posterior, <span class="dv">1</span>, entropy))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>LCA2_entropy <span class="ot">&lt;-</span> (error_prior <span class="sc">-</span> error_post) <span class="sc">/</span> error_prior</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>LCA2_entropy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4055313</code></pre>
</div>
</div>
<p>This entropy is extremely low. Notice the fit is better, and you may well find the entropy of LC3, etc. is higher.</p>
</section>
</section>
<section id="interpretation-of-output" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-of-output">Interpretation of Output</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model_2class<span class="sc">$</span>P)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6304614 0.3695386</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model_2class<span class="sc">$</span>probs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$symptom1
              Pr(1)     Pr(2)
class 1:  0.5122364 0.4877636
class 2:  0.5386575 0.4613425

$symptom2
              Pr(1)       Pr(2)     Pr(3)
class 1:  0.1009128 0.518461219 0.3806260
class 2:  0.6342460 0.003058431 0.3626956

$symptom3
              Pr(1)     Pr(2)
class 1:  0.5584610 0.4415390
class 2:  0.4543825 0.5456175

$symptom4
              Pr(1)     Pr(2)     Pr(3)
class 1:  0.3600143 0.2617789 0.3782068
class 2:  0.2842054 0.4572148 0.2585798</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(model_2class<span class="sc">$</span>posterior)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          [,1]        [,2]
[1,] 0.9979742 0.002025753
[2,] 0.9979742 0.002025753
[3,] 0.6683339 0.331666081
[4,] 0.6598969 0.340103109
[5,] 0.4409736 0.559026359
[6,] 0.5711748 0.428825155</code></pre>
</div>
</div>
<p><strong>Interpretation</strong>: After estimating the model, poLCA assigns approximately 63% of the sample to Class 1 and 37% to Class 2. These are model-implied proportions, meaning the algorithm estimates that these are the relative sizes of the two latent classes in the population based on response patterns.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 81%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>What It Means</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>$P</code></td>
<td>Proportion of total sample estimated to belong to each class</td>
<td></td>
</tr>
<tr class="even">
<td><code>$probs</code></td>
<td>Probability of each item response given class membership (Pr(item class))</td>
<td></td>
</tr>
<tr class="odd">
<td><code>$posterior</code></td>
<td>For each individual: probability of being in each class given their response pattern</td>
<td></td>
</tr>
</tbody>
</table>
<section id="class-proportions" class="level4">
<h4 class="anchored" data-anchor-id="class-proportions">Class Proportions</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Class</th>
<th>Estimated Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Class 1</td>
<td>63.0%</td>
</tr>
<tr class="even">
<td>Class 2</td>
<td>36.9%</td>
</tr>
</tbody>
</table>
</section>
<section id="item-response-probabilities" class="level4">
<h4 class="anchored" data-anchor-id="item-response-probabilities">Item Response Probabilities</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Symptom</th>
<th>Response</th>
<th>Class 1</th>
<th>Class 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>symptom1</td>
<td>1</td>
<td>0.512</td>
<td>0.539</td>
</tr>
<tr class="even">
<td></td>
<td>2</td>
<td>0.488</td>
<td>0.461</td>
</tr>
<tr class="odd">
<td><strong>symptom2</strong></td>
<td>1</td>
<td>0.101</td>
<td><strong>0.634</strong></td>
</tr>
<tr class="even">
<td></td>
<td>2</td>
<td><strong>0.518</strong></td>
<td>0.003</td>
</tr>
<tr class="odd">
<td></td>
<td>3</td>
<td>0.381</td>
<td>0.363</td>
</tr>
<tr class="even">
<td>symptom3</td>
<td>1</td>
<td><strong>0.558</strong></td>
<td>0.454</td>
</tr>
<tr class="odd">
<td></td>
<td>2</td>
<td>0.442</td>
<td><strong>0.546</strong></td>
</tr>
<tr class="even">
<td>symptom4</td>
<td>1</td>
<td>0.360</td>
<td>0.284</td>
</tr>
<tr class="odd">
<td></td>
<td>2</td>
<td>0.262</td>
<td>0.457</td>
</tr>
<tr class="even">
<td></td>
<td>3</td>
<td>0.378</td>
<td>0.259</td>
</tr>
</tbody>
</table>
<p>Each row gives the probability that a person in Class 1 or Class 2 endorses a specific response level on a particular symptom. For instance, under symptom2, Class 1 has a 51.8% probability of responding with 2, while Class 2 has a 63.4% probability of responding with 1.</p>
<p>This format makes it easy to see how well the classes are separated. You can spot which symptoms help tell the classes apart by looking for:</p>
<ul>
<li><p>Big differences between classes for the same response option.</p></li>
<li><p>Clear patterns where one class is much more likely—or unlikely—to give a certain response (for example, Class 2 almost never chooses response 2 for symptom2).</p></li>
</ul>
<p>This helps assess both class separation (how different the classes are) and within-class consistency (how similar responses are within each class).</p>
<p>Here is how I would describe the classes: Class 1 (63% of respondents) is the class of respondents who endorse symptom 3 with high probability, whereas class 2 (~37%) endorse sympton 2 with high probability.</p>
</section>
</section>
</section>
<section id="visualization-of-item-response-probabilities" class="level1">
<h1>Visualization of Item-Response Probabilities</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'purrr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:base':

    %||%</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract and reshape item-response probabilities</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>probs_long <span class="ot">&lt;-</span> model_2class<span class="sc">$</span>probs <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">imap_dfr</span>(<span class="sc">~</span>{</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as_tibble</span>(.x) <span class="sc">%&gt;%</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">Class =</span> <span class="fu">row_number</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">pivot_longer</span>(<span class="sc">-</span>Class, <span class="at">names_to =</span> <span class="st">"Response"</span>, <span class="at">values_to =</span> <span class="st">"Probability"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">Symptom =</span> .y)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(probs_long, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(Class), <span class="at">y =</span> Probability, <span class="at">fill =</span> Response)) <span class="sc">+</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Symptom, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Item-Response Probabilities by Class"</span>,</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Latent Class"</span>,</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Pr(Response | Class)"</span>,</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Response"</span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lca_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Symptom</th>
<th>Class Separation</th>
<th>Discriminative Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Symptom 1</td>
<td>Low</td>
<td>Weak</td>
</tr>
<tr class="even">
<td>Symptom 2</td>
<td>High</td>
<td>Strong</td>
</tr>
<tr class="odd">
<td>Symptom 3</td>
<td>Moderate</td>
<td>Good</td>
</tr>
<tr class="even">
<td>Symptom 4</td>
<td>Moderate</td>
<td>Fair</td>
</tr>
</tbody>
</table>
</section>
<section id="extensions" class="level1">
<h1>Extensions</h1>
<p>Next time we will look at extensions.</p>
</section>
<section id="model-assessment-recap" class="level1">
<h1>Model Assessment Recap</h1>
<ul>
<li><strong>Fit indices:</strong> Lower BIC and AIC indicate better models.</li>
<li><strong>Entropy:</strong> Higher entropy (closer to 1) means clearer class separation.</li>
<li><strong>Posterior classification probabilities:</strong> Evaluate individual classification confidence.</li>
<li><strong>Class prevalence and response patterns:</strong> Interpret substantive meaning of each class.</li>
</ul>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>LCA is a powerful technique for uncovering latent subgroups in cross-sectional data. This tutorial showed how to use <code>poLCA</code> for categorical indicators and <code>tidyLPA</code> for continuous indicators, how to evaluate and compare models, and how to extend the analysis to multigroup and multilevel settings. This foundation can support deeper exploration of typologies in developmental, health, and behavioral research.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>